apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
  namespace: mlops-platform
  annotations:
    # Le script IRSA remplace/ajoute cette annotation avec le rôle réel.
    eks.amazonaws.com/role-arn: arn:aws:iam::590183937685:role/mlops-n4-mlflow
